version: '3'

services:
  master:
    image: jmetermaster:v1
    container_name: master
    tty: true
    networks:
    - jmeternetwork
  slave:
    image: jmeterslave:v1
    tty: true
    networks:
    - jmeternetwork
    volumes:
    - .:/scripts

networks:
  jmeternetwork:
    driver: bridge