version: '3'

services:
  webapp:
    image: webapp:v1
    container_name: webapp
  client:
    image: client:v1
    container_name: client
    tty: true
  server:
    image: server:v1
    command: /jmeter/apache-jmeter-5.3/bin/jmeter-server -n

networks:
  default:
    external:
      name: jmeter