version: '3'

services:
  webapp:
    image: webapp:v1
    container_name: webapp
    networks:
    - jmeternetwork
    ports:
    - "80:9090"
  master:
    image: jmetermaster:v1
    container_name: master
    tty: true
    networks:
    - jmeternetwork
  slave:
    image: jmeterslave:v1
    tty: true
    networks:
    - jmeternetwork

networks:
  jmeternetwork:
    driver: bridge